### ISSUE TITLE
Unable to find template when trying to {% include %}

### ISSUE THREAD

**Issue by johndwells** [fruitstudios/craft-searchit#1]
I've tried including a template as indicated in the docs, but I'm getting a Twig Template Loading Error that it cannot be found. The template is definitely in our project's `templates` folder.

It seems that the view path isn't being set to the correct context; if I add this to line 50 of `models/ElementFilter.php` then it works as intended:

```
Craft::$app->getView()->setTemplateMode(\craft\web\View::TEMPLATE_MODE_SITE);
```

This plugin is AWESOME. :D

**Comment by johndwells** [comment]
(It's possible that you'll need to set the view back once done rendering the dynamic content)

**Comment by samhibberd** [comment]
Hey @johndwells thanks for reporting, the twig validation was a rather last minute addition and we forgot to switch up the template mode when validating, all fixed. Also caught an exception issue too, so thats a bonus. Just releasing 1.0.1. Thanks and please keep the feedback coming, we really want to keep improving this one!!
