### ISSUE TITLE
DB queries and speed issue

### ISSUE THREAD

**Issue by bphippen** [fruitstudios/craft-searchit#16]
Doing some testing with the plugin and came across this problem.

I have 2 active filters on one entry type. This entry has a fairly large Neo field with some related entries as fields within it.

Loading and saving an entry **without** Searchit enabled creates 160 or so DB requests in the CP with a load time of around 2.5 seconds. 

However **with** Searchit enabled, that number shoots up to around 3500 or so and the load time is above 10 seconds.

Craft Pro 3.1.19
Searchit 1.0.7

**Comment by piotrpog** [comment]
I also have this problem. This occured after i recently updated Craft CMS, i had about 1 month old version earlier. In my case only one filter existing also slows down control panel. Even dashboard loads slower, creating 1500 DB queries. When i disable searchit plugin, problems are gone.

I would approciate if it was fixed urgently because it's hard to use control panel now.

**Comment by john-henry** [comment]
Can concur here. In recent Craft update I've had to disable SearchIt as loading any entry **listing** takes 10+ seconds. Totally unusable presently. Reduced it back to just a simple Category filter and experienced the same

**Comment by samhibberd** [comment]
Thanks for reporting, we are on the case!

**Comment by john-henry** [comment]
@samhibberd Any luck with this? Client has more of less had plugin disabled since I installed it for them

**Comment by piotrpog** [comment]
Same thing happened with my client. I would appreciate if we were given some kind of update.

**Comment by samhibberd** [comment]
A fix for this is going to be a priority next week, sorry for the delay.

**Comment by samhibberd** [comment]
Hey all, I’ve tested a fix for this locally and wondered if anyone could take it for a spin on a large site, see 1.0.8 on the develop branch?

**Comment by bphippen** [comment]
On first look, the issue seems to be fixed, thanks so much! I'll do some more testing and let you know if I run across anything weird.

**Comment by john-henry** [comment]
@samhibberd giving it a whirl this evening

**Comment by samhibberd** [comment]
@bphippen - Great stuff.
@john-henry - I will await your feedback tonight before I get it released.

Thanks folks.

**Comment by john-henry** [comment]
@samhibberd Looks much better to me right now. Can't find issue

**Comment by samhibberd** [comment]
Ok great! Will get a release out today.

**Comment by samhibberd** [comment]
Fixed as a part of 1.0.8. Thanks
