### ISSUE TITLE
Not able to get filters to work

### ISSUE THREAD

**Issue by stevehurst** [fruitstudios/craft-searchit#3]
I'm testing this plugin with one section that has multiple entry types and categories assigned to entries. Neither filter is working.

First for entry types:

```
{ "filter":"type:default", "label":"Article" },
{ "filter":"type:video", "label":"Video" }
```

Second for categories:

```
{% for category in craft.categories.group('viewpointsSections').level('1').all() %}
   {{ ({
       filter: {
           descendantOf: category.id
       },
       label: category.title
   })|json_encode() }}{{ not loop.last ? ',' }}
{% endfor %}
```

When I use the dropdown filter, the list returns no entries. I've updated my search indexes as well. Is there something I'm missing?

**Comment by stevehurst** [comment]
I was able to get categories to work by updating the code:

```
{% for category in craft.categories.group('viewpointsSections').level('1').all() %}
   {{ ({
        filter: {
            relatedTo: {
                element: category.id,
                field: 'viewpointsSections'
            }
        },
       label: category.title
   })|json_encode() }}{{ not loop.last ? ',' }}
{% endfor %}
```

Still not able to get filtering by entry type working. I'm guessing this will need more complex Twig than JSON filters. Please advise.

**Comment by shornuk** [comment]
Hi @stevehurst , 

Pleased to see you got the categories working. With regards to the entry types, from first glance that looks right. 
Can you try setting it up as a manual filter? 
Add the label and then put `{"type":"default"}` in the filter. 

Something like this...
![screen shot 2018-10-22 at 19 57 43](https://user-images.githubusercontent.com/2061819/47312651-d67d9d00-d634-11e8-955b-7f578da91f37.png)
Then let us know how you get on. 👍🏻

**Comment by stevehurst** [comment]
@shornuk that did the trick! Some adjustment to the instructions might be in order to make formatting needs clearer. I thought simply "type: video" went into this filter space on the manual option.

Thanks for the quick response!

**Comment by shornuk** [comment]
Awesome. Yea, we know the docs need some improving. We're planning on introducing a whole raft of examples that should help give good starting points.
