### ISSUE TITLE
Is this plugin abandoned?

### ISSUE THREAD

**Issue by kylecotter** [fruitstudios/craft-searchit#30]
We use this plugin frequently as it offers a great experience for content editors.

Just curious if this plugin is actively being developed as it's been a while since a release and Craft has had a number of UI adjustments to the toolbar since.

Thanks!

**Comment by ben-callaway** [comment]
Hi @kylecotter Not at all, it's about to get some love. We've been under a rock for some time and are now getting back up to speed on everything. Hold tight!

**Comment by kylecotter** [comment]
Sweet! Thanks so much for the update!
