### ISSUE TITLE
I have a problem when make update

### ISSUE THREAD

**Issue by danireginatto** [fruitstudios/craft-searchit#9]
Yii Migration Tool (based on Yii v2.0.15.1)

Exception: Argument 1 passed to craft\services\Sections::getSectionById() must be of the type integer, string given, called in /opt/bitnami/apache2/htdocs/cms/vendor/fruitstudios/searchit/src/migrations/m190204_000001_source_to_uids.php on line 47 (/opt/bitnami/apache2/htdocs/cms/vendor/craftcms/cms/src/services/Sections.php:290)
#0 /opt/bitnami/apache2/htdocs/cms/vendor/fruitstudios/searchit/src/migrations/m190204_000001_source_to_uids.php(47): craft\services\Sections->getSectionById('fb341e27-9cc7-4...')
#1 /opt/bitnami/apache2/htdocs/cms/vendor/fruitstudios/searchit/src/migrations/m190204_000001_source_to_uids.php(22): fruitstudios\searchit\migrations\m190204_000001_source_to_uids->_sourcesToUid()
#2 /opt/bitnami/apache2/htdocs/cms/vendor/craftcms/cms/src/db/Migration.php(56): fruitstudios\searchit\migrations\m190204_000001_source_to_uids->safeUp()
#3 /opt/bitnami/apache2/htdocs/cms/vendor/craftcms/cms/src/db/MigrationManager.php(243): craft\db\Migration->up(true)
#4 /opt/bitnami/apache2/htdocs/cms/vendor/craftcms/cms/src/db/MigrationManager.php(163): craft\db\MigrationManager->migrateUp(Object(fruitstudios\searchit\migrations\m190204_000001_source_to_uids))
#5 /opt/bitnami/apache2/htdocs/cms/vendor/craftcms/cms/src/services/Updates.php(223): craft\db\MigrationManager->up()
#6 /opt/bitnami/apache2/htdocs/cms/vendor/craftcms/cms/src/console/controllers/MigrateController.php(252): craft\services\Updates->runMigrations(Array)
#7 [internal function]: craft\console\controllers\MigrateController->actionAll()
#8 /opt/bitnami/apache2/htdocs/cms/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#9 /opt/bitnami/apache2/htdocs/cms/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#10 /opt/bitnami/apache2/htdocs/cms/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('all', Array)
#11 /opt/bitnami/apache2/htdocs/cms/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('all', Array)
#12 /opt/bitnami/apache2/htdocs/cms/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/all', Array)
#13 /opt/bitnami/apache2/htdocs/cms/vendor/craftcms/cms/src/console/Application.php(93): yii\console\Application->runAction('migrate/all', Array)
#14 /opt/bitnami/apache2/htdocs/cms/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('migrate/all', Array)
#15 /opt/bitnami/apache2/htdocs/cms/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#16 /opt/bitnami/apache2/htdocs/cms/craft(22): yii\base\Application->run()
#17 {main}
Exception 'craft\errors\MigrateException' with message 'An error occurred while migrating Searchit.'

in /opt/bitnami/apache2/htdocs/cms/vendor/craftcms/cms/src/services/Updates.php:231

Stack trace:
#0 /opt/bitnami/apache2/htdocs/cms/vendor/craftcms/cms/src/console/controllers/MigrateController.php(252): craft\services\Updates->runMigrations(Array)
#1 [internal function]: craft\console\controllers\MigrateController->actionAll()
#2 /opt/bitnami/apache2/htdocs/cms/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#3 /opt/bitnami/apache2/htdocs/cms/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#4 /opt/bitnami/apache2/htdocs/cms/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('all', Array)
#5 /opt/bitnami/apache2/htdocs/cms/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('all', Array)
#6 /opt/bitnami/apache2/htdocs/cms/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/all', Array)
#7 /opt/bitnami/apache2/htdocs/cms/vendor/craftcms/cms/src/console/Application.php(93): yii\console\Application->runAction('migrate/all', Array)
#8 /opt/bitnami/apache2/htdocs/cms/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('migrate/all', Array)
#9 /opt/bitnami/apache2/htdocs/cms/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#10 /opt/bitnami/apache2/htdocs/cms/craft(22): yii\base\Application->run()
#11 {main}

**Comment by samhibberd** [comment]
Fixed in 1.0.5. Thanks for reporting.

**Comment by danireginatto** [comment]
Tks a lot
